# Site settings
title: Patryk Tokarski Blog
email: 
description: "Insightful description."
baseurl: ""
url: "https://tokarskipatryk.github.io"
twitter_username: tokarskipatryk
github_username:  tokarooo

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
